name: flutter_googlemap_firestore
description: Flutter Google Map with Firestore start kit

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^0.5.20+3
  cloud_firestore: ^0.12.9
  http: ^0.12.0+1
  json_serializable: ^2.0.2

dev_dependencies:
  pedantic: ^1.4.0
  build_runner: ^1.2.7

flutter:

  uses-material-design: true
